version: '3.3'
services:
  fluentd:
    build: ./fluentd
    container_name: fluentd
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"

  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: elasticsearch
    expose:
      - 9200
    volumes:
      - ./es_data/:/usr/share/elasticsearch/data/
    environment:
      TZ: Asia/Tokyo

  kibana:
    image: kibana:6.6.2
    container_name: kibana
    links: [elasticsearch]
    ports:
      - "5601:5601"
      
networks:
  default:
    external:
      name: shared

