version: '3.3'
services:
  web:
    image: fukuyama012/cycle-reminder
    container_name: web
    command: revel run -a github.com/fukuyama012/cycle-reminder/service/web prod
    expose:
      - 9000
    env_file: .env.test
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db
    restart: always

  db:
    image: fukuyama012/mysql5.7
    container_name: db
    env_file: .env.test
    environment:
      TZ: "Asia/Tokyo"
    restart: always

networks:
  default:
    external:
      name: shared