version: '3.3'
services:
  web:
    build:
      context: web
    container_name: web
    command: revel run -a github.com/fukuyama012/cycle-reminder/service/web
    expose:
      - 9000
    env_file: .env.test
    environment:
      TZ: Asia/Tokyo
      VIRTUAL_HOST: ${DOMAIN} # ホストの環境変数にドメイン名を設定しておく
    depends_on:
      - db
    restart: always

  db:
    image: fukuyama012/mysql5.7
    container_name: db
    env_file: .env.test
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/init/:/docker-entrypoint-initdb.d
    restart: always

networks:
  default:
    external:
      name: shared