version: '3.3'
services:
  web:
    command: revel run -a github.com/fukuyama012/cycle-reminder/service/web
    volumes:
      - ./web/:/go/src/github.com/fukuyama012/cycle-reminder/service/web/

  db:
    ports:
      - "3306:3306"

