version: "3.3"
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      TZ: "Asia/Tokyo"
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"
        
networks:
  default:
    external:
      name: shared